version: '2'

services:
  db:
    image: linuxserver/mariadb:110.3.18mariabionic-ls37
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=  # make sure to set your password here
      - TZ=Europe/Berlin # change for your time zone
      - MYSQL_DATABASE=ncdb
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=xxxx
    volumes:
      - /path/to/data:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  cache:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /path/to/data:/data
    entrypoint: redis-server --appendonly yes
    restart: always
 
  app:
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8080:80
      - 443:443
    links:
      - db
      - cache
    volumes:
      - /path/to/data:/data
      - /path/to/appdata:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_PASSWORD=  # make sure to set your password here
      - MYSQL_DATABASE=ncdb
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=cache
      - NEXTCLOUD_ADMIN_USER= # make sure to set your user here
      - NEXTCLOUD_ADMIN_PASSWORD=  # make sure to set your password here
